import { Attraction } from "./types";

// Mock data for Hong Kong attractions
export const mockAttractions: Attraction[] = [
  {
    id: "1",
    name: "Victoria Peak",
    description:
      "Hong Kong's most popular attraction offering stunning panoramic views of the city skyline and harbor.",
    location: "Central & Western District",
    rating: 4.5,
    reviewCount: 12847,
    category: "Scenic Views",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "7:00 AM - 12:00 AM",
    priceRange: "HK$65-99",
  },
  {
    id: "2",
    name: "Star Ferry",
    description:
      "Historic ferry service providing scenic harbor crossings between Hong Kong Island and Kowloon.",
    location: "Victoria Harbour",
    rating: 4.3,
    reviewCount: 8932,
    category: "Transportation",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "6:30 AM - 11:30 PM",
    priceRange: "HK$3-7",
  },
  {
    id: "3",
    name: "Temple Street Night Market",
    description:
      "Vibrant night market famous for street food, fortune telling, and bargain shopping.",
    location: "Yau Ma Tei, Kowloon",
    rating: 4.2,
    reviewCount: 15672,
    category: "Markets",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "6:00 PM - 12:00 AM",
    priceRange: "HK$20-150",
  },
  {
    id: "4",
    name: "Tian Tan Buddha",
    description:
      "Massive bronze Buddha statue and spiritual landmark on Lantau Island.",
    location: "Ngong Ping, Lantau Island",
    rating: 4.4,
    reviewCount: 9876,
    category: "Religious Sites",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "10:00 AM - 5:30 PM",
    priceRange: "Free",
  },
  {
    id: "5",
    name: "Avenue of Stars",
    description:
      "Waterfront promenade celebrating Hong Kong's film industry with stunning harbor views.",
    location: "Tsim Sha Tsui",
    rating: 4.1,
    reviewCount: 7654,
    category: "Entertainment",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "24 hours",
    priceRange: "Free",
  },
  {
    id: "6",
    name: "Hong Kong Disneyland",
    description:
      "Magical theme park featuring Disney attractions, shows, and character experiences.",
    location: "Lantau Island",
    rating: 4.3,
    reviewCount: 23456,
    category: "Theme Parks",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "10:00 AM - 9:00 PM",
    priceRange: "HK$639-739",
  },
  {
    id: "7",
    name: "Man Mo Temple",
    description:
      "Historic Taoist temple dedicated to literature and war gods, famous for giant incense coils.",
    location: "Sheung Wan",
    rating: 4.2,
    reviewCount: 5432,
    category: "Religious Sites",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "8:00 AM - 6:00 PM",
    priceRange: "Free",
  },
  {
    id: "8",
    name: "Ocean Park",
    description:
      "Marine life theme park combining entertainment, education and conservation.",
    location: "Aberdeen",
    rating: 4.2,
    reviewCount: 18765,
    category: "Theme Parks",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "10:00 AM - 6:00 PM",
    priceRange: "HK$498-623",
  },
  {
    id: "9",
    name: "Wong Tai Sin Temple",
    description:
      "Colorful Taoist temple famous for fortune-telling and wish fulfillment.",
    location: "Wong Tai Sin",
    rating: 4.0,
    reviewCount: 6789,
    category: "Religious Sites",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "7:00 AM - 5:30 PM",
    priceRange: "Free",
  },
  {
    id: "10",
    name: "Tsim Sha Tsui Promenade",
    description:
      "Scenic waterfront walkway with views of Hong Kong Island skyline and harbor.",
    location: "Tsim Sha Tsui",
    rating: 4.4,
    reviewCount: 11234,
    category: "Scenic Views",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "24 hours",
    priceRange: "Free",
  },
  {
    id: "11",
    name: "Ladies' Market",
    description:
      "Bustling street market in Mong Kok known for bargain shopping and local atmosphere.",
    location: "Mong Kok",
    rating: 3.9,
    reviewCount: 8765,
    category: "Markets",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "12:00 PM - 11:00 PM",
    priceRange: "HK$10-200",
  },
  {
    id: "12",
    name: "Hong Kong Museum of History",
    description:
      "Comprehensive museum showcasing Hong Kong's rich cultural and natural history.",
    location: "Tsim Sha Tsui East",
    rating: 4.3,
    reviewCount: 4567,
    category: "Museums",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "10:00 AM - 6:00 PM",
    priceRange: "HK$10-30",
  },
  {
    id: "13",
    name: "Central Mid-Levels Escalator",
    description:
      "World's longest outdoor covered escalator system connecting Central to Mid-Levels.",
    location: "Central",
    rating: 3.8,
    reviewCount: 3456,
    category: "Transportation",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "6:00 AM - 12:00 AM",
    priceRange: "Free",
  },
  {
    id: "14",
    name: "Hong Kong Space Museum",
    description:
      "Interactive science museum with planetarium and space exploration exhibits.",
    location: "Tsim Sha Tsui",
    rating: 4.1,
    reviewCount: 5678,
    category: "Museums",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "1:00 PM - 9:00 PM",
    priceRange: "HK$24-32",
  },
  {
    id: "15",
    name: "Dragon's Back Trail",
    description:
      "Scenic hiking trail offering spectacular views of the South China Sea and coastline.",
    location: "Shek O",
    rating: 4.6,
    reviewCount: 7890,
    category: "Nature & Hiking",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "24 hours",
    priceRange: "Free",
  },
  {
    id: "16",
    name: "Lan Kwai Fong",
    description:
      "Famous nightlife district with bars, clubs, and restaurants in Central.",
    location: "Central",
    rating: 4.0,
    reviewCount: 9876,
    category: "Nightlife",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "6:00 PM - 4:00 AM",
    priceRange: "HK$100-500",
  },
  {
    id: "17",
    name: "Chi Lin Nunnery",
    description:
      "Serene Buddhist temple complex featuring traditional wooden architecture and gardens.",
    location: "Diamond Hill",
    rating: 4.3,
    reviewCount: 4321,
    category: "Religious Sites",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "9:00 AM - 4:30 PM",
    priceRange: "Free",
  },
  {
    id: "18",
    name: "Repulse Bay",
    description:
      "Popular beach destination with golden sand, clear water, and beachfront dining.",
    location: "Southern District",
    rating: 4.2,
    reviewCount: 6543,
    category: "Beaches",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "24 hours",
    priceRange: "Free",
  },
  {
    id: "19",
    name: "Hong Kong Park",
    description:
      "Urban oasis featuring aviaries, conservatory, and traditional gardens in the city center.",
    location: "Admiralty",
    rating: 4.1,
    reviewCount: 3789,
    category: "Parks",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "6:00 AM - 11:00 PM",
    priceRange: "Free",
  },
  {
    id: "20",
    name: "PMQ (Police Married Quarters)",
    description:
      "Creative hub in heritage building featuring local designers, cafes, and cultural events.",
    location: "Central",
    rating: 4.0,
    reviewCount: 2345,
    category: "Culture & Arts",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "7:00 AM - 11:00 PM",
    priceRange: "Free-HK$200",
  },
  {
    id: "21",
    name: "Stanley Market",
    description:
      "Seaside market town famous for bargain shopping, dining, and beach activities.",
    location: "Stanley",
    rating: 4.0,
    reviewCount: 5432,
    category: "Markets",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "9:00 AM - 6:00 PM",
    priceRange: "HK$20-300",
  },
  {
    id: "22",
    name: "Ngong Ping 360",
    description:
      "Cable car journey offering breathtaking views en route to Lantau Island attractions.",
    location: "Lantau Island",
    rating: 4.2,
    reviewCount: 8901,
    category: "Transportation",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "10:00 AM - 6:30 PM",
    priceRange: "HK$235-320",
  },
  {
    id: "23",
    name: "Jumbo Kingdom",
    description:
      "Iconic floating restaurant offering traditional Cantonese cuisine on Aberdeen Harbour.",
    location: "Aberdeen",
    rating: 3.8,
    reviewCount: 4567,
    category: "Dining",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "11:00 AM - 11:30 PM",
    priceRange: "HK$300-800",
  },
  {
    id: "24",
    name: "Tai Kwun Heritage & Arts",
    description:
      "Historic police compound transformed into cultural destination with exhibitions and performances.",
    location: "Central",
    rating: 4.4,
    reviewCount: 3456,
    category: "Culture & Arts",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "10:00 AM - 11:00 PM",
    priceRange: "Free-HK$150",
  },
  {
    id: "25",
    name: "Sik Sik Yuen Wong Tai Sin Temple",
    description:
      "Vibrant Taoist temple complex known for its colorful architecture and fortune telling.",
    location: "Wong Tai Sin",
    rating: 4.1,
    reviewCount: 6789,
    category: "Religious Sites",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "7:00 AM - 5:30 PM",
    priceRange: "Free",
  },
  {
    id: "26",
    name: "Hong Kong Wetland Park",
    description:
      "Ecological attraction showcasing wetland habitats, wildlife, and environmental education.",
    location: "Tin Shui Wai",
    rating: 4.2,
    reviewCount: 2345,
    category: "Nature & Wildlife",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "10:00 AM - 5:00 PM",
    priceRange: "HK$30-50",
  },
  {
    id: "27",
    name: "Clock Tower",
    description:
      "Historic landmark and remnant of the former Kowloon-Canton Railway terminus.",
    location: "Tsim Sha Tsui",
    rating: 3.7,
    reviewCount: 1234,
    category: "Historical Sites",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "24 hours",
    priceRange: "Free",
  },
  {
    id: "28",
    name: "Goldfish Market",
    description:
      "Unique street market specializing in tropical fish, aquarium supplies, and pet accessories.",
    location: "Mong Kok",
    rating: 3.9,
    reviewCount: 2876,
    category: "Markets",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "10:00 AM - 8:00 PM",
    priceRange: "HK$10-500",
  },
  {
    id: "29",
    name: "IFC Mall & Sky100",
    description:
      "Premier shopping destination with observation deck offering 360-degree city views.",
    location: "Central",
    rating: 4.3,
    reviewCount: 7654,
    category: "Shopping",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "10:00 AM - 10:00 PM",
    priceRange: "HK$168-268",
  },
  {
    id: "30",
    name: "Flower Market",
    description:
      "Colorful street market filled with fresh flowers, plants, and gardening supplies.",
    location: "Mong Kok",
    rating: 4.0,
    reviewCount: 3210,
    category: "Markets",
    imageUrl: "/api/placeholder/300/200",
    openingHours: "7:00 AM - 8:00 PM",
    priceRange: "HK$10-200",
  },
];
