import { drizzle } from "drizzle-orm/neon-serverless";
import { attractions } from "../db/schema";
import { config } from "dotenv";

// Load environment variables
config({ path: ".env" });

if (!process.env.DATABASE_URL) {
    throw new Error("DATABASE_URL is not set");
}

const db = drizzle(process.env.DATABASE_URL);

// Seed data based on mockData.ts
const attractionsData = [
    {
        id: "1",
        name: "Victoria Peak",
        description: "Hong Kong's most popular attraction offering stunning panoramic views of the city skyline and harbor.",
        location: "Central & Western District",
        rating: 4.5,
        reviewCount: 12847,
        category: "Scenic Views",
        imageUrl: "/api/placeholder/300/200",
        openingHours: "7:00 AM - 12:00 AM",
        priceRange: "HK$65-99",
        latitude: 22.2708,
        longitude: 114.1501,
    },
    {
        id: "2",
        name: "Star Ferry",
        description: "Historic ferry service providing scenic harbor crossings between Hong Kong Island and Kowloon.",
        location: "Victoria Harbour",
        rating: 4.3,
        reviewCount: 8932,
        category: "Transportation",
        imageUrl: "/api/placeholder/300/200",
        openingHours: "6:30 AM - 11:30 PM",
        priceRange: "HK$3-7",
        latitude: 22.2944,
        longitude: 114.1697,
    },
    {
        id: "3",
        name: "Temple Street Night Market",
        description: "Vibrant night market famous for street food, fortune telling, and bargain shopping.",
        location: "Yau Ma Tei, Kowloon",
        rating: 4.2,
        reviewCount: 15672,
        category: "Markets",
        imageUrl: "/api/placeholder/300/200",
        openingHours: "6:00 PM - 12:00 AM",
        priceRange: "HK$20-150",
        latitude: 22.3106,
        longitude: 114.1714,
    },
    {
        id: "4",
        name: "Tian Tan Buddha",
        description: "Massive bronze Buddha statue and spiritual landmark on Lantau Island.",
        location: "Ngong Ping, Lantau Island",
        rating: 4.4,
        reviewCount: 9876,
        category: "Religious Sites",
        imageUrl: "/api/placeholder/300/200",
        openingHours: "10:00 AM - 5:30 PM",
        priceRange: "Free",
        latitude: 22.2544,
        longitude: 113.9051,
    },
    {
        id: "5",
        name: "Avenue of Stars",
        description: "Waterfront promenade celebrating Hong Kong's film industry with stunning harbor views.",
        location: "Tsim Sha Tsui",
        rating: 4.1,
        reviewCount: 7654,
        category: "Entertainment",
        imageUrl: "/api/placeholder/300/200",
        openingHours: "24 hours",
        priceRange: "Free",
        latitude: 22.2940,
        longitude: 114.1722,
    },
    {
        id: "6",
        name: "Hong Kong Disneyland",
        description: "Magical theme park featuring Disney attractions, shows, and character experiences.",
        location: "Lantau Island",
        rating: 4.3,
        reviewCount: 23456,
        category: "Theme Parks",
        imageUrl: "/api/placeholder/300/200",
        openingHours: "10:00 AM - 9:00 PM",
        priceRange: "HK$639-739",
        latitude: 22.3129,
        longitude: 114.0413,
    },
    {
        id: "7",
        name: "Man Mo Temple",
        description: "Historic Taoist temple dedicated to literature and war gods, famous for giant incense coils.",
        location: "Sheung Wan",
        rating: 4.2,
        reviewCount: 5432,
        category: "Religious Sites",
        imageUrl: "/api/placeholder/300/200",
        openingHours: "8:00 AM - 6:00 PM",
        priceRange: "Free",
        latitude: 22.2815,
        longitude: 114.1474,
    },
    {
        id: "8",
        name: "Ocean Park",
        description: "Marine life theme park combining entertainment, education and conservation.",
        location: "Aberdeen",
        rating: 4.2,
        reviewCount: 18765,
        category: "Theme Parks",
        imageUrl: "/api/placeholder/300/200",
        openingHours: "10:00 AM - 6:00 PM",
        priceRange: "HK$498-623",
        latitude: 22.2462,
        longitude: 114.1759,
    },
    {
        id: "9",
        name: "Wong Tai Sin Temple",
        description: "Colorful Taoist temple famous for fortune-telling and wish fulfillment.",
        location: "Wong Tai Sin",
        rating: 4.0,
        reviewCount: 6789,
        category: "Religious Sites",
        imageUrl: "/api/placeholder/300/200",
        openingHours: "7:00 AM - 5:30 PM",
        priceRange: "Free",
        latitude: 22.3421,
        longitude: 114.1938,
    },
    {
        id: "10",
        name: "Tsim Sha Tsui Promenade",
        description: "Scenic waterfront walkway with views of Hong Kong Island skyline and harbor.",
        location: "Tsim Sha Tsui",
        rating: 4.4,
        reviewCount: 11234,
        category: "Scenic Views",
        imageUrl: "/api/placeholder/300/200",
        openingHours: "24 hours",
        priceRange: "Free",
        latitude: 22.2940,
        longitude: 114.1722,
    },
    {
        id: "11",
        name: "Ladies' Market",
        description: "Bustling street market in Mong Kok known for bargain shopping and local atmosphere.",
        location: "Mong Kok",
        rating: 3.9,
        reviewCount: 8765,
        category: "Markets",
        imageUrl: "/api/placeholder/300/200",
        openingHours: "12:00 PM - 11:00 PM",
        priceRange: "HK$10-200",
        latitude: 22.3193,
        longitude: 114.1694,
    },
    {
        id: "12",
        name: "Hong Kong Museum of History",
        description: "Comprehensive museum showcasing Hong Kong's rich cultural and natural history.",
        location: "Tsim Sha Tsui East",
        rating: 4.3,
        reviewCount: 4567,
        category: "Museums",
        imageUrl: "/api/placeholder/300/200",
        openingHours: "10:00 AM - 6:00 PM",
        priceRange: "HK$10-30",
        latitude: 22.3015,
        longitude: 114.1779,
    },
    {
        id: "13",
        name: "Central Mid-Levels Escalator",
        description: "World's longest outdoor covered escalator system connecting Central to Mid-Levels.",
        location: "Central",
        rating: 3.8,
        reviewCount: 3456,
        category: "Transportation",
        imageUrl: "/api/placeholder/300/200",
        openingHours: "6:00 AM - 12:00 AM",
        priceRange: "Free",
        latitude: 22.2810,
        longitude: 114.1556,
    },
    {
        id: "14",
        name: "Hong Kong Space Museum",
        description: "Interactive science museum with planetarium and space exploration exhibits.",
        location: "Tsim Sha Tsui",
        rating: 4.1,
        reviewCount: 5678,
        category: "Museums",
        imageUrl: "/api/placeholder/300/200",
        openingHours: "1:00 PM - 9:00 PM",
        priceRange: "HK$24-32",
        latitude: 22.2947,
        longitude: 114.1694,
    },
    {
        id: "15",
        name: "Dragon's Back Trail",
        description: "Scenic hiking trail offering spectacular views of the South China Sea and coastline.",
        location: "Shek O",
        rating: 4.6,
        reviewCount: 7890,
        category: "Nature & Hiking",
        imageUrl: "/api/placeholder/300/200",
        openingHours: "24 hours",
        priceRange: "Free",
        latitude: 22.2260,
        longitude: 114.2372,
    },
    {
        id: "16",
        name: "Lan Kwai Fong",
        description: "Famous nightlife district with bars, clubs, and restaurants in Central.",
        location: "Central",
        rating: 4.0,
        reviewCount: 9876,
        category: "Nightlife",
        imageUrl: "/api/placeholder/300/200",
        openingHours: "6:00 PM - 4:00 AM",
        priceRange: "HK$100-500",
        latitude: 22.2808,
        longitude: 114.1555,
    },
    {
        id: "17",
        name: "Chi Lin Nunnery",
        description: "Serene Buddhist temple complex featuring traditional wooden architecture and gardens.",
        location: "Diamond Hill",
        rating: 4.3,
        reviewCount: 4321,
        category: "Religious Sites",
        imageUrl: "/api/placeholder/300/200",
        openingHours: "9:00 AM - 4:30 PM",
        priceRange: "Free",
        latitude: 22.3387,
        longitude: 114.2052,
    },
    {
        id: "18",
        name: "Repulse Bay",
        description: "Popular beach destination with golden sand, clear water, and beachfront dining.",
        location: "Southern District",
        rating: 4.2,
        reviewCount: 6543,
        category: "Beaches",
        imageUrl: "/api/placeholder/300/200",
        openingHours: "24 hours",
        priceRange: "Free",
        latitude: 22.2364,
        longitude: 114.1975,
    },
    {
        id: "19",
        name: "Hong Kong Park",
        description: "Urban oasis featuring aviaries, conservatory, and traditional gardens in the city center.",
        location: "Admiralty",
        rating: 4.1,
        reviewCount: 3789,
        category: "Parks",
        imageUrl: "/api/placeholder/300/200",
        openingHours: "6:00 AM - 11:00 PM",
        priceRange: "Free",
        latitude: 22.2777,
        longitude: 114.1610,
    },
    {
        id: "20",
        name: "PMQ (Police Married Quarters)",
        description: "Creative hub in heritage building featuring local designers, cafes, and cultural events.",
        location: "Central",
        rating: 4.0,
        reviewCount: 2345,
        category: "Culture & Arts",
        imageUrl: "/api/placeholder/300/200",
        openingHours: "7:00 AM - 11:00 PM",
        priceRange: "Free-HK$200",
        latitude: 22.2838,
        longitude: 114.1520,
    },
];

async function seedAttractions() {
    console.log("Starting to seed attractions...");

    // Insert attractions one by one to avoid Neon serverless issues
    let inserted = 0;
    for (const attraction of attractionsData) {
        await db.insert(attractions).values(attraction).onConflictDoNothing();
        inserted++;
        console.log(`Inserted attraction ${inserted}/${attractionsData.length}: ${attraction.name}`);
    }
}

// Run the seed function
seedAttractions()
    .then(() => {
        console.log("Seeding completed successfully!");
        process.exit(0);
    })
    .catch((error) => {
        console.error("Seeding failed:", error);
        process.exit(1);
    });
