import { drizzle } from "drizzle-orm/neon-serverless";
import { trips } from "../db/schema";
import { nanoid } from "nanoid";
import { config } from "dotenv";

// Load environment variables
config({ path: ".env" });

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL is not set");
}

const db = drizzle(process.env.DATABASE_URL);

const tripCategories = [
  "restaurant",
  "shopping",
  "entertainment",
  "nature",
  "culture",
] as const;

const sampleTrips = [
  // Free trips
  {
    name: "Central Heritage Walk",
    description:
      "Explore historic Central district with guided audio tour through colonial architecture and modern landmarks",
    duration: "2h 30m",
    category: "culture",
    isPremium: false,
    isLocked: false,
    tokenCost: 0,
    transportMode: ["walk"],
    itinerary: [
      {
        id: "stop1",
        name: "Former Legislative Council Building",
        description:
          "Historic government building with neoclassical architecture",
        duration: "20m",
        location: "Central",
        category: "culture",
        order: 1,
        nextTransport: {
          method: "walk",
          duration: "3m",
          distance: "250m",
          instructions: "Walk east along Des Voeux Road Central",
        },
      },
      {
        id: "stop2",
        name: "Statue Square",
        description: "Historic public square with colonial monuments",
        duration: "15m",
        location: "Central",
        category: "culture",
        order: 2,
        nextTransport: {
          method: "walk",
          duration: "2m",
          distance: "150m",
          instructions: "Cross the road to Chater Road",
        },
      },
      {
        id: "stop3",
        name: "Hong Kong Club Building",
        description: "Colonial architecture and exclusive gentleman's club",
        duration: "15m",
        location: "Central",
        category: "culture",
        order: 3,
        nextTransport: {
          method: "walk",
          duration: "5m",
          distance: "400m",
          instructions: "Walk north to Queen's Road Central",
        },
      },
      {
        id: "stop4",
        name: "Old Bank of China Building",
        description: "Art Deco architecture and historic banking landmark",
        duration: "20m",
        location: "Central",
        category: "culture",
        order: 4,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Tai Kwun Art Discovery",
    description:
      "Contemporary art galleries and historic police station with interactive exhibits",
    duration: "1h 45m",
    category: "entertainment",
    isPremium: false,
    isLocked: false,
    tokenCost: 0,
    transportMode: ["walk", "car"],
    itinerary: [
      {
        id: "stop1",
        name: "Heritage Gallery",
        description: "Historical exhibits about Hong Kong's police history",
        duration: "30m",
        location: "Tai Kwun",
        category: "culture",
        order: 1,
        nextTransport: {
          method: "walk",
          duration: "5m",
          distance: "100m",
          instructions: "Walk through the courtyard to the main building",
        },
      },
      {
        id: "stop2",
        name: "Contemporary Gallery",
        description: "Modern art displays and rotating exhibitions",
        duration: "45m",
        location: "Tai Kwun",
        category: "entertainment",
        order: 2,
        nextTransport: {
          method: "walk",
          duration: "3m",
          distance: "80m",
          instructions: "Walk to the historic prison cells area",
        },
      },
      {
        id: "stop3",
        name: "Old Prison Cells",
        description:
          "Preserved Victorian-era prison cells with interactive displays",
        duration: "30m",
        location: "Tai Kwun",
        category: "culture",
        order: 3,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Nature Photography Tour",
    description:
      "Capture stunning landscapes in Hong Kong's nature reserves with professional tips",
    duration: "4h 00m",
    category: "nature",
    isPremium: false,
    isLocked: false,
    tokenCost: 0,
    transportMode: ["car", "bike"],
    itinerary: [
      {
        id: "stop1",
        name: "Dragon's Back Trail",
        description:
          "Scenic hiking trail with panoramic views of the South China Sea",
        duration: "2h",
        location: "Shek O",
        category: "nature",
        order: 1,
        nextTransport: {
          method: "car",
          duration: "15m",
          distance: "8km",
          instructions: "Drive along Shek O Road towards Big Wave Bay",
        },
      },
      {
        id: "stop2",
        name: "Big Wave Bay",
        description: "Coastal photography spot with golden sand beach",
        duration: "1h",
        location: "Big Wave Bay",
        category: "nature",
        order: 2,
        nextTransport: {
          method: "car",
          duration: "10m",
          distance: "5km",
          instructions: "Drive north to Tai Tam Country Park",
        },
      },
      {
        id: "stop3",
        name: "Tai Tam Reservoir",
        description:
          "Historic reservoir with Victorian architecture and forest views",
        duration: "45m",
        location: "Tai Tam",
        category: "nature",
        order: 3,
        nextTransport: {
          method: "car",
          duration: "8m",
          distance: "3km",
          instructions: "Drive to nearby lookout point",
        },
      },
      {
        id: "stop4",
        name: "Mount Butler Lookout",
        description: "Elevated viewpoint with panoramic city and harbor views",
        duration: "15m",
        location: "Tai Tam",
        category: "nature",
        order: 4,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Shopping District Explorer",
    description:
      "Discover hidden gems in bustling shopping areas and local markets",
    duration: "2h 15m",
    category: "shopping",
    isPremium: false,
    isLocked: false,
    tokenCost: 0,
    transportMode: ["walk", "car"],
    itinerary: [
      {
        id: "stop1",
        name: "Causeway Bay Shopping",
        description:
          "Major shopping district with international brands and local boutiques",
        duration: "1h",
        location: "Causeway Bay",
        category: "shopping",
        order: 1,
        nextTransport: {
          method: "walk",
          duration: "8m",
          distance: "600m",
          instructions: "Walk south on Russell Street towards Times Square",
        },
      },
      {
        id: "stop2",
        name: "Times Square",
        description:
          "Multi-level shopping mall with restaurants and entertainment",
        duration: "45m",
        location: "Causeway Bay",
        category: "shopping",
        order: 2,
        nextTransport: {
          method: "walk",
          duration: "5m",
          distance: "300m",
          instructions: "Walk to nearby fashion street",
        },
      },
      {
        id: "stop3",
        name: "Fashion Walk",
        description:
          "Trendy outdoor shopping area with designer stores and cafes",
        duration: "30m",
        location: "Causeway Bay",
        category: "shopping",
        order: 3,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Street Food Adventure",
    description: "Taste authentic local street food across traditional markets",
    duration: "3h 00m",
    category: "restaurant",
    isPremium: false,
    isLocked: false,
    tokenCost: 0,
    transportMode: ["walk"],
    itinerary: [
      {
        id: "stop1",
        name: "Temple Street Night Market",
        description: "Famous street food market with local delicacies",
        duration: "1h",
        location: "Yau Ma Tei",
        category: "restaurant",
        order: 1,
        nextTransport: {
          method: "walk",
          duration: "12m",
          distance: "800m",
          instructions: "Walk north through Nathan Road to Ladies' Market",
        },
      },
      {
        id: "stop2",
        name: "Ladies' Market",
        description: "Local street food stalls and traditional snacks",
        duration: "45m",
        location: "Mong Kok",
        category: "restaurant",
        order: 2,
        nextTransport: {
          method: "walk",
          duration: "8m",
          distance: "500m",
          instructions: "Walk to nearby wet market area",
        },
      },
      {
        id: "stop3",
        name: "Goldfish Market Food Stalls",
        description: "Hidden food gems near the famous goldfish market",
        duration: "45m",
        location: "Mong Kok",
        category: "restaurant",
        order: 3,
        nextTransport: {
          method: "walk",
          duration: "5m",
          distance: "300m",
          instructions: "Walk to traditional tea house",
        },
      },
      {
        id: "stop4",
        name: "Traditional Tea House",
        description: "Authentic dim sum and tea experience",
        duration: "30m",
        location: "Mong Kok",
        category: "restaurant",
        order: 4,
        nextTransport: null,
      },
    ],
  },
  // Premium locked trips
  {
    name: "Premium Food Trail",
    description:
      "Exclusive dining experience with local chef guides at Michelin-starred restaurants",
    duration: "3h 15m",
    category: "restaurant",
    isPremium: true,
    isLocked: true,
    tokenCost: 50,
    transportMode: ["car", "walk"],
    itinerary: [
      {
        id: "stop1",
        name: "Michelin Star Restaurant",
        description: "Fine dining experience with tasting menu",
        duration: "2h",
        location: "Central",
        category: "restaurant",
        order: 1,
        nextTransport: {
          method: "car",
          duration: "8m",
          distance: "2km",
          instructions: "Private car transfer to chef's studio",
        },
      },
      {
        id: "stop2",
        name: "Private Chef Demo",
        description: "Exclusive cooking demonstration with celebrity chef",
        duration: "1h 15m",
        location: "Central",
        category: "restaurant",
        order: 2,
        nextTransport: {
          method: "walk",
          duration: "5m",
          distance: "200m",
          instructions: "Walk to premium market",
        },
      },
      {
        id: "stop3",
        name: "Gourmet Ingredient Market",
        description: "Exclusive access to premium ingredients with sommelier",
        duration: "45m",
        location: "Central",
        category: "restaurant",
        order: 3,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Premium Cultural Experience",
    description:
      "VIP access to museums and cultural sites with private curator tours",
    duration: "5h 30m",
    category: "culture",
    isPremium: true,
    isLocked: true,
    tokenCost: 75,
    transportMode: ["car"],
    itinerary: [
      {
        id: "stop1",
        name: "Hong Kong Museum of Art",
        description: "VIP private tour with curator-led exclusive access",
        duration: "2h",
        location: "Tsim Sha Tsui",
        category: "culture",
        order: 1,
        nextTransport: {
          method: "walk",
          duration: "3m",
          distance: "200m",
          instructions: "Walk along the waterfront promenade",
        },
      },
      {
        id: "stop2",
        name: "Hong Kong Space Museum",
        description: "Exclusive planetarium show with interactive exhibits",
        duration: "1h 30m",
        location: "Tsim Sha Tsui",
        category: "culture",
        order: 2,
        nextTransport: {
          method: "taxi",
          duration: "12m",
          distance: "4.5km",
          instructions: "Take taxi through Cross-Harbour Tunnel to Central",
        },
      },
      {
        id: "stop3",
        name: "Private Collection Viewing",
        description: "Rare artifacts viewing in exclusive private gallery",
        duration: "2h",
        location: "Central",
        category: "culture",
        order: 3,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Luxury Harbor Cruise",
    description:
      "Private yacht tour around Victoria Harbor with gourmet dining",
    duration: "4h 00m",
    category: "entertainment",
    isPremium: true,
    isLocked: true,
    tokenCost: 100,
    transportMode: ["car"],
    itinerary: [
      {
        id: "stop1",
        name: "Private Yacht Boarding",
        description: "Welcome aboard luxury yacht with champagne reception",
        duration: "30m",
        location: "Central Pier",
        category: "entertainment",
        order: 1,
        nextTransport: {
          method: "yacht",
          duration: "15m",
          distance: "3km",
          instructions: "Cruise to Victoria Harbor viewing area",
        },
      },
      {
        id: "stop2",
        name: "Victoria Harbor Cruise",
        description: "Scenic harbor cruise with city skyline views",
        duration: "2h",
        location: "Victoria Harbor",
        category: "entertainment",
        order: 2,
        nextTransport: {
          method: "yacht",
          duration: "10m",
          distance: "2km",
          instructions: "Navigate to exclusive dining area",
        },
      },
      {
        id: "stop3",
        name: "Gourmet Yacht Dining",
        description: "Multi-course meal prepared by private chef",
        duration: "1h 20m",
        location: "Private Waters",
        category: "entertainment",
        order: 3,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Exclusive Shopping Experience",
    description:
      "Personal shopping assistant at luxury boutiques with VIP access",
    duration: "3h 30m",
    category: "shopping",
    isPremium: true,
    isLocked: true,
    tokenCost: 60,
    transportMode: ["car"],
    itinerary: [
      {
        id: "stop1",
        name: "Luxury Boutiques",
        description: "Personal shopping service with VIP access",
        duration: "1h 30m",
        location: "Central",
        category: "shopping",
        order: 1,
        nextTransport: {
          method: "car",
          duration: "5m",
          distance: "1km",
          instructions: "Private car to designer showroom",
        },
      },
      {
        id: "stop2",
        name: "Designer Showroom",
        description: "Exclusive access to latest collections",
        duration: "1h",
        location: "Central",
        category: "shopping",
        order: 2,
        nextTransport: {
          method: "walk",
          duration: "3m",
          distance: "150m",
          instructions: "Walk to private styling suite",
        },
      },
      {
        id: "stop3",
        name: "Private Fitting Room",
        description: "Exclusive styling session with professional stylist",
        duration: "1h",
        location: "Central",
        category: "shopping",
        order: 3,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Premium Nature Retreat",
    description: "Private guided hike with luxury picnic and spa treatments",
    duration: "6h 00m",
    category: "nature",
    isPremium: true,
    isLocked: true,
    tokenCost: 80,
    transportMode: ["car"],
    itinerary: [
      {
        id: "stop1",
        name: "Private Hiking Trail",
        description: "Guided nature walk",
        duration: "3h",
        location: "Sai Kung",
        category: "nature",
        order: 1,
      },
      {
        id: "stop2",
        name: "Luxury Picnic",
        description: "Gourmet outdoor dining",
        duration: "1h 30m",
        location: "Sai Kung",
        category: "nature",
        order: 2,
      },
      {
        id: "stop3",
        name: "Spa Treatment",
        description: "Outdoor massage therapy",
        duration: "1h 30m",
        location: "Sai Kung",
        category: "nature",
        order: 3,
      },
    ],
  },
  // Additional free trips
  {
    name: "Temple Hopping Tour",
    description:
      "Visit ancient temples and learn about local spiritual practices",
    duration: "2h 45m",
    category: "culture",
    isPremium: false,
    isLocked: false,
    tokenCost: 0,
    transportMode: ["walk", "car"],
    itinerary: [
      {
        id: "stop1",
        name: "Man Mo Temple",
        description: "Historic Taoist temple",
        duration: "45m",
        location: "Sheung Wan",
        category: "culture",
        order: 1,
      },
      {
        id: "stop2",
        name: "Wong Tai Sin Temple",
        description: "Famous fortune telling temple",
        duration: "1h",
        location: "Wong Tai Sin",
        category: "culture",
        order: 2,
      },
      {
        id: "stop3",
        name: "Chi Lin Nunnery",
        description: "Buddhist wooden temple",
        duration: "1h",
        location: "Diamond Hill",
        category: "culture",
        order: 3,
      },
    ],
  },
  {
    name: "Local Markets Adventure",
    description:
      "Explore traditional wet markets and learn about local ingredients",
    duration: "2h 00m",
    category: "shopping",
    isPremium: false,
    isLocked: false,
    tokenCost: 0,
    transportMode: ["walk"],
    itinerary: [
      {
        id: "stop1",
        name: "Graham Street Market",
        description:
          "Traditional wet market with fresh produce and local ingredients",
        duration: "45m",
        location: "Central",
        category: "shopping",
        order: 1,
        nextTransport: {
          method: "walk",
          duration: "10m",
          distance: "700m",
          instructions: "Walk through Central to Wan Chai",
        },
      },
      {
        id: "stop2",
        name: "Tai Yuen Street Market",
        description: "Famous toy street market with vintage collectibles",
        duration: "45m",
        location: "Wan Chai",
        category: "shopping",
        order: 2,
        nextTransport: {
          method: "walk",
          duration: "8m",
          distance: "500m",
          instructions: "Walk to nearby wet market",
        },
      },
      {
        id: "stop3",
        name: "Wan Chai Market",
        description: "Local market with traditional goods and street food",
        duration: "30m",
        location: "Wan Chai",
        category: "shopping",
        order: 3,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Rooftop Bars Circuit",
    description: "Visit the best rooftop bars with stunning city views",
    duration: "3h 30m",
    category: "entertainment",
    isPremium: false,
    isLocked: false,
    tokenCost: 0,
    transportMode: ["walk", "car"],
    itinerary: [
      {
        id: "stop1",
        name: "Sky Bar",
        description: "Panoramic city views with craft cocktails",
        duration: "1h 15m",
        location: "Central",
        category: "entertainment",
        order: 1,
        nextTransport: {
          method: "car",
          duration: "15m",
          distance: "3km",
          instructions: "Take taxi through tunnel to Tsim Sha Tsui",
        },
      },
      {
        id: "stop2",
        name: "Rooftop Lounge",
        description: "Harbor view cocktails and live music",
        duration: "1h 30m",
        location: "Tsim Sha Tsui",
        category: "entertainment",
        order: 2,
        nextTransport: {
          method: "walk",
          duration: "8m",
          distance: "600m",
          instructions: "Walk along waterfront promenade",
        },
      },
      {
        id: "stop3",
        name: "Waterfront Bar",
        description: "Open-air bar with Symphony of Lights view",
        duration: "45m",
        location: "Tsim Sha Tsui",
        category: "entertainment",
        order: 3,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Hiking Trail Explorer",
    description:
      "Discover scenic hiking trails suitable for all fitness levels",
    duration: "3h 15m",
    category: "nature",
    isPremium: false,
    isLocked: false,
    tokenCost: 0,
    transportMode: ["car", "walk"],
    itinerary: [
      {
        id: "stop1",
        name: "Lion Pavilion",
        description: "Easy hiking trail with harbor views",
        duration: "1h",
        location: "Tsim Sha Tsui",
        category: "nature",
        order: 1,
        nextTransport: {
          method: "car",
          duration: "20m",
          distance: "8km",
          instructions: "Drive up to The Peak via Peak Road",
        },
      },
      {
        id: "stop2",
        name: "Victoria Peak Garden",
        description: "Scenic viewpoint with panoramic city views",
        duration: "1h",
        location: "The Peak",
        category: "nature",
        order: 2,
        nextTransport: {
          method: "walk",
          duration: "10m",
          distance: "500m",
          instructions: "Walk to Sky Terrace area",
        },
      },
      {
        id: "stop3",
        name: "Sky Terrace 428",
        description: "360-degree observation deck with photo opportunities",
        duration: "45m",
        location: "The Peak",
        category: "nature",
        order: 3,
        nextTransport: {
          method: "walk",
          duration: "5m",
          distance: "200m",
          instructions: "Walk to nature trail entrance",
        },
      },
      {
        id: "stop4",
        name: "Peak Circle Walk",
        description: "Easy nature walk through lush vegetation",
        duration: "30m",
        location: "The Peak",
        category: "nature",
        order: 4,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Dim Sum Crawl",
    description: "Traditional dim sum experience across famous tea houses",
    duration: "2h 30m",
    category: "restaurant",
    isPremium: false,
    isLocked: false,
    tokenCost: 0,
    transportMode: ["walk", "car"],
    itinerary: [
      {
        id: "stop1",
        name: "Maxim's Palace",
        description: "Traditional dim sum with authentic pushcart service",
        duration: "1h",
        location: "Central",
        category: "restaurant",
        order: 1,
        nextTransport: {
          method: "walk",
          duration: "8m",
          distance: "600m",
          instructions: "Walk through Central district to Wellington Street",
        },
      },
      {
        id: "stop2",
        name: "Lin Heung Tea House",
        description: "Historic old-style tea house with communal seating",
        duration: "45m",
        location: "Central",
        category: "restaurant",
        order: 2,
        nextTransport: {
          method: "walk",
          duration: "10m",
          distance: "700m",
          instructions: "Walk to famous local dim sum spot",
        },
      },
      {
        id: "stop3",
        name: "Kam Wah Cafe",
        description: "Local favorite for pineapple buns and milk tea",
        duration: "30m",
        location: "Central",
        category: "restaurant",
        order: 3,
        nextTransport: {
          method: "walk",
          duration: "5m",
          distance: "300m",
          instructions: "Walk to traditional bakery",
        },
      },
      {
        id: "stop4",
        name: "Tai Cheong Bakery",
        description: "Famous for egg tarts and traditional pastries",
        duration: "15m",
        location: "Central",
        category: "restaurant",
        order: 4,
        nextTransport: null,
      },
    ],
  },
  // More premium trips
  {
    name: "Private Art Collection Tour",
    description:
      "Exclusive access to private art collections with expert commentary",
    duration: "4h 30m",
    category: "culture",
    isPremium: true,
    isLocked: true,
    tokenCost: 90,
    transportMode: ["car"],
    itinerary: [
      {
        id: "stop1",
        name: "Private Gallery",
        description: "Exclusive art viewing with collector's personal tour",
        duration: "1h 30m",
        location: "Central",
        category: "culture",
        order: 1,
        nextTransport: {
          method: "car",
          duration: "15m",
          distance: "6km",
          instructions: "Private car transfer to Wong Chuk Hang art district",
        },
      },
      {
        id: "stop2",
        name: "Artist Studio Visit",
        description: "Meet renowned local artists in their working studios",
        duration: "1h 30m",
        location: "Wong Chuk Hang",
        category: "culture",
        order: 2,
        nextTransport: {
          method: "walk",
          duration: "5m",
          distance: "200m",
          instructions: "Walk to contemporary art space",
        },
      },
      {
        id: "stop3",
        name: "Contemporary Art Space",
        description: "Cutting-edge installations and experimental art",
        duration: "1h",
        location: "Wong Chuk Hang",
        category: "culture",
        order: 3,
        nextTransport: {
          method: "walk",
          duration: "3m",
          distance: "100m",
          instructions: "Walk to private viewing room",
        },
      },
      {
        id: "stop4",
        name: "Rare Art Collection",
        description: "Viewing of rare and historical art pieces",
        duration: "30m",
        location: "Wong Chuk Hang",
        category: "culture",
        order: 4,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Luxury Spa & Wellness",
    description: "Premium spa treatments with traditional Chinese medicine",
    duration: "5h 00m",
    category: "entertainment",
    isPremium: true,
    isLocked: true,
    tokenCost: 85,
    transportMode: ["car"],
    itinerary: [
      {
        id: "stop1",
        name: "Luxury Spa Reception",
        description: "Welcome treatment with herbal tea and consultation",
        duration: "30m",
        location: "Central",
        category: "entertainment",
        order: 1,
        nextTransport: {
          method: "walk",
          duration: "2m",
          distance: "50m",
          instructions: "Walk to treatment rooms",
        },
      },
      {
        id: "stop2",
        name: "Premium Massage Therapy",
        description: "Full body therapeutic massage with premium oils",
        duration: "2h",
        location: "Central",
        category: "entertainment",
        order: 2,
        nextTransport: {
          method: "walk",
          duration: "3m",
          distance: "100m",
          instructions: "Walk to TCM consultation room",
        },
      },
      {
        id: "stop3",
        name: "Traditional Medicine Consultation",
        description: "Comprehensive TCM health assessment and treatment",
        duration: "1h 30m",
        location: "Central",
        category: "entertainment",
        order: 3,
        nextTransport: {
          method: "walk",
          duration: "2m",
          distance: "80m",
          instructions: "Walk to relaxation lounge",
        },
      },
      {
        id: "stop4",
        name: "Wellness Relaxation Lounge",
        description: "Private relaxation with healthy refreshments",
        duration: "1h",
        location: "Central",
        category: "entertainment",
        order: 4,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Gourmet Market Tour",
    description:
      "Private chef-guided tour of premium food markets with tastings",
    duration: "3h 45m",
    category: "restaurant",
    isPremium: true,
    isLocked: true,
    tokenCost: 65,
    transportMode: ["car", "walk"],
    itinerary: [
      {
        id: "stop1",
        name: "Premium Food Market",
        description:
          "Chef-guided tasting of premium ingredients and delicacies",
        duration: "1h 30m",
        location: "Central",
        category: "restaurant",
        order: 1,
        nextTransport: {
          method: "walk",
          duration: "5m",
          distance: "300m",
          instructions: "Walk to specialty spice shop",
        },
      },
      {
        id: "stop2",
        name: "Artisan Spice Shop",
        description: "Exclusive spice and seasoning tasting experience",
        duration: "45m",
        location: "Central",
        category: "restaurant",
        order: 2,
        nextTransport: {
          method: "car",
          duration: "10m",
          distance: "2km",
          instructions: "Private car to cooking studio",
        },
      },
      {
        id: "stop3",
        name: "Private Cooking Class",
        description: "Hands-on cooking lesson with professional chef",
        duration: "1h 30m",
        location: "Central",
        category: "restaurant",
        order: 3,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Designer Shopping Experience",
    description: "Access to designer showrooms with personal stylist service",
    duration: "4h 15m",
    category: "shopping",
    isPremium: true,
    isLocked: true,
    tokenCost: 70,
    transportMode: ["car"],
    itinerary: [
      {
        id: "stop1",
        name: "Designer Showroom",
        description: "Exclusive fashion viewing with latest collections",
        duration: "1h 30m",
        location: "Central",
        category: "shopping",
        order: 1,
        nextTransport: {
          method: "car",
          duration: "8m",
          distance: "1.5km",
          instructions: "Private car to luxury boutique district",
        },
      },
      {
        id: "stop2",
        name: "High-End Boutique Tour",
        description: "Curated selection of luxury brands with VIP access",
        duration: "1h 15m",
        location: "Central",
        category: "shopping",
        order: 2,
        nextTransport: {
          method: "walk",
          duration: "3m",
          distance: "150m",
          instructions: "Walk to personal styling suite",
        },
      },
      {
        id: "stop3",
        name: "Personal Styling Session",
        description: "One-on-one styling consultation with fashion expert",
        duration: "1h 30m",
        location: "Central",
        category: "shopping",
        order: 3,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Private Island Experience",
    description:
      "Exclusive access to private island with water sports and dining",
    duration: "7h 00m",
    category: "nature",
    isPremium: true,
    isLocked: true,
    tokenCost: 120,
    transportMode: ["car"],
    itinerary: [
      {
        id: "stop1",
        name: "Private Ferry",
        description: "Luxury boat transfer",
        duration: "1h",
        location: "Central Pier",
        category: "nature",
        order: 1,
      },
      {
        id: "stop2",
        name: "Private Beach",
        description: "Exclusive beach access",
        duration: "4h",
        location: "Private Island",
        category: "nature",
        order: 2,
      },
      {
        id: "stop3",
        name: "Gourmet Beach Dining",
        description: "Chef-prepared meal",
        duration: "2h",
        location: "Private Island",
        category: "nature",
        order: 3,
      },
    ],
  },
  // Additional free trips to reach 30 total
  {
    name: "Street Art Discovery",
    description:
      "Find hidden street art and murals across different neighborhoods",
    duration: "2h 20m",
    category: "culture",
    isPremium: false,
    isLocked: false,
    tokenCost: 0,
    transportMode: ["walk"],
    itinerary: [
      {
        id: "stop1",
        name: "PMQ Street Art",
        description: "Creative hub murals and artist workshops",
        duration: "45m",
        location: "Central",
        category: "culture",
        order: 1,
        nextTransport: {
          method: "walk",
          duration: "12m",
          distance: "900m",
          instructions: "Walk uphill to Sheung Wan via Hollywood Road",
        },
      },
      {
        id: "stop2",
        name: "Sheung Wan Graffiti",
        description: "Local street art and hidden murals",
        duration: "45m",
        location: "Sheung Wan",
        category: "culture",
        order: 2,
        nextTransport: {
          method: "walk",
          duration: "8m",
          distance: "500m",
          instructions: "Walk to historic temple area",
        },
      },
      {
        id: "stop3",
        name: "Man Mo Temple Street Art",
        description: "Traditional and modern art fusion near historic temple",
        duration: "30m",
        location: "Sheung Wan",
        category: "culture",
        order: 3,
        nextTransport: {
          method: "walk",
          duration: "5m",
          distance: "200m",
          instructions: "Walk to underground art gallery",
        },
      },
      {
        id: "stop4",
        name: "Underground Art Space",
        description: "Hidden gallery featuring local emerging artists",
        duration: "20m",
        location: "Sheung Wan",
        category: "culture",
        order: 4,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Night Market Food Tour",
    description: "Experience the vibrant night market culture and street food",
    duration: "3h 00m",
    category: "restaurant",
    isPremium: false,
    isLocked: false,
    tokenCost: 0,
    transportMode: ["walk", "car"],
    itinerary: [
      {
        id: "stop1",
        name: "Temple Street Night Market",
        description: "Famous night market with authentic street food",
        duration: "1h",
        location: "Yau Ma Tei",
        category: "restaurant",
        order: 1,
        nextTransport: {
          method: "walk",
          duration: "10m",
          distance: "700m",
          instructions: "Walk north to Mong Kok via Nathan Road",
        },
      },
      {
        id: "stop2",
        name: "Fa Yuen Street Market",
        description: "Local food stalls and traditional snacks",
        duration: "45m",
        location: "Mong Kok",
        category: "restaurant",
        order: 2,
        nextTransport: {
          method: "walk",
          duration: "5m",
          distance: "300m",
          instructions: "Walk to nearby night food street",
        },
      },
      {
        id: "stop3",
        name: "Sai Yeung Choi Street Food",
        description: "Bustling pedestrian street with diverse food options",
        duration: "45m",
        location: "Mong Kok",
        category: "restaurant",
        order: 3,
        nextTransport: {
          method: "walk",
          duration: "8m",
          distance: "400m",
          instructions: "Walk to traditional dessert shop",
        },
      },
      {
        id: "stop4",
        name: "Traditional Dessert Shop",
        description: "Local desserts and sweet treats to end the night",
        duration: "30m",
        location: "Mong Kok",
        category: "restaurant",
        order: 4,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Vintage Shopping Hunt",
    description: "Hunt for vintage treasures and unique finds in local shops",
    duration: "2h 45m",
    category: "shopping",
    isPremium: false,
    isLocked: false,
    tokenCost: 0,
    transportMode: ["walk"],
    itinerary: [
      {
        id: "stop1",
        name: "Cat Street Antiques",
        description: "Vintage antique shops with unique collectibles",
        duration: "1h",
        location: "Sheung Wan",
        category: "shopping",
        order: 1,
        nextTransport: {
          method: "walk",
          duration: "8m",
          distance: "600m",
          instructions: "Walk down to Central via steep streets",
        },
      },
      {
        id: "stop2",
        name: "Second-hand Bookstores",
        description: "Rare book hunting and vintage publications",
        duration: "45m",
        location: "Central",
        category: "shopping",
        order: 2,
        nextTransport: {
          method: "walk",
          duration: "5m",
          distance: "300m",
          instructions: "Walk to vintage clothing district",
        },
      },
      {
        id: "stop3",
        name: "Vintage Clothing Boutiques",
        description: "Retro fashion and designer vintage pieces",
        duration: "45m",
        location: "Central",
        category: "shopping",
        order: 3,
        nextTransport: {
          method: "walk",
          duration: "3m",
          distance: "150m",
          instructions: "Walk to record shop",
        },
      },
      {
        id: "stop4",
        name: "Vinyl Record Shop",
        description: "Rare vinyl records and vintage music memorabilia",
        duration: "15m",
        location: "Central",
        category: "shopping",
        order: 4,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Live Music Venues Tour",
    description: "Discover the local music scene across intimate venues",
    duration: "4h 00m",
    category: "entertainment",
    isPremium: false,
    isLocked: false,
    tokenCost: 0,
    transportMode: ["walk", "car"],
    itinerary: [
      {
        id: "stop1",
        name: "Jazz Club",
        description: "Intimate jazz performances with craft cocktails",
        duration: "1h 30m",
        location: "Central",
        category: "entertainment",
        order: 1,
        nextTransport: {
          method: "car",
          duration: "12m",
          distance: "4km",
          instructions: "Take taxi to Causeway Bay music district",
        },
      },
      {
        id: "stop2",
        name: "Indie Music Venue",
        description: "Local band performances and emerging artists",
        duration: "1h 30m",
        location: "Causeway Bay",
        category: "entertainment",
        order: 2,
        nextTransport: {
          method: "walk",
          duration: "5m",
          distance: "300m",
          instructions: "Walk to acoustic music bar",
        },
      },
      {
        id: "stop3",
        name: "Acoustic Music Bar",
        description:
          "Cozy venue featuring acoustic sets and singer-songwriters",
        duration: "1h",
        location: "Causeway Bay",
        category: "entertainment",
        order: 3,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Waterfront Cycling Tour",
    description: "Scenic cycling route along the harbor with multiple stops",
    duration: "3h 30m",
    category: "nature",
    isPremium: false,
    isLocked: false,
    tokenCost: 0,
    transportMode: ["bike"],
    itinerary: [
      {
        id: "stop1",
        name: "Tsim Sha Tsui Promenade",
        description: "Scenic harbor cycling path with city skyline views",
        duration: "1h",
        location: "Tsim Sha Tsui",
        category: "nature",
        order: 1,
        nextTransport: {
          method: "bike",
          duration: "15m",
          distance: "3km",
          instructions: "Cycle west along the waterfront bike path",
        },
      },
      {
        id: "stop2",
        name: "West Kowloon Cultural District",
        description: "Modern waterfront area with art installations",
        duration: "1h 15m",
        location: "West Kowloon",
        category: "nature",
        order: 2,
        nextTransport: {
          method: "bike",
          duration: "10m",
          distance: "2km",
          instructions: "Cycle to waterfront park area",
        },
      },
      {
        id: "stop3",
        name: "Kowloon Park Cycling Area",
        description: "Green space with cycling paths and rest areas",
        duration: "45m",
        location: "Tsim Sha Tsui",
        category: "nature",
        order: 3,
        nextTransport: {
          method: "bike",
          duration: "8m",
          distance: "1.5km",
          instructions: "Cycle back to waterfront viewing area",
        },
      },
      {
        id: "stop4",
        name: "Avenue of Stars",
        description: "Waterfront promenade celebrating Hong Kong cinema",
        duration: "30m",
        location: "Tsim Sha Tsui",
        category: "nature",
        order: 4,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Tea Culture Experience",
    description: "Learn about traditional Chinese tea culture and ceremonies",
    duration: "2h 15m",
    category: "culture",
    isPremium: false,
    isLocked: false,
    tokenCost: 0,
    transportMode: ["walk"],
    itinerary: [
      {
        id: "stop1",
        name: "Traditional Tea House",
        description: "Authentic tea ceremony demonstration with master",
        duration: "45m",
        location: "Central",
        category: "culture",
        order: 1,
        nextTransport: {
          method: "walk",
          duration: "8m",
          distance: "500m",
          instructions: "Walk to specialty tea shop",
        },
      },
      {
        id: "stop2",
        name: "Premium Tea Shop",
        description: "Tea tasting and education about different varieties",
        duration: "45m",
        location: "Central",
        category: "culture",
        order: 2,
        nextTransport: {
          method: "walk",
          duration: "5m",
          distance: "200m",
          instructions: "Walk to tea garden terrace",
        },
      },
      {
        id: "stop3",
        name: "Rooftop Tea Garden",
        description: "Peaceful tea experience with city views",
        duration: "45m",
        location: "Central",
        category: "culture",
        order: 3,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Local Craft Beer Tour",
    description:
      "Sample craft beers from local breweries and learn brewing process",
    duration: "3h 15m",
    category: "restaurant",
    isPremium: false,
    isLocked: false,
    tokenCost: 0,
    transportMode: ["walk", "car"],
    itinerary: [
      {
        id: "stop1",
        name: "Local Brewery",
        description: "Craft beer tasting with brewing process tour",
        duration: "1h 15m",
        location: "Wong Chuk Hang",
        category: "restaurant",
        order: 1,
        nextTransport: {
          method: "car",
          duration: "15m",
          distance: "6km",
          instructions: "Take taxi to Central beer district",
        },
      },
      {
        id: "stop2",
        name: "Craft Beer Bar",
        description: "Selection of local and international craft beers",
        duration: "1h",
        location: "Central",
        category: "restaurant",
        order: 2,
        nextTransport: {
          method: "walk",
          duration: "5m",
          distance: "200m",
          instructions: "Walk to outdoor beer garden",
        },
      },
      {
        id: "stop3",
        name: "Beer Garden",
        description: "Outdoor beer experience with local food pairings",
        duration: "1h",
        location: "Central",
        category: "restaurant",
        order: 3,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Boutique Shopping Walk",
    description: "Explore unique boutiques and local designer stores",
    duration: "2h 30m",
    category: "shopping",
    isPremium: false,
    isLocked: false,
    tokenCost: 0,
    transportMode: ["walk"],
    itinerary: [
      {
        id: "stop1",
        name: "Local Designer Boutiques",
        description: "Independent fashion stores with unique Hong Kong designs",
        duration: "45m",
        location: "Central",
        category: "shopping",
        order: 1,
        nextTransport: {
          method: "walk",
          duration: "10m",
          distance: "700m",
          instructions: "Walk uphill to Sheung Wan via Hollywood Road",
        },
      },
      {
        id: "stop2",
        name: "Artisan Craft Shops",
        description: "Handmade goods and traditional crafts",
        duration: "45m",
        location: "Sheung Wan",
        category: "shopping",
        order: 2,
        nextTransport: {
          method: "walk",
          duration: "5m",
          distance: "300m",
          instructions: "Walk to jewelry design studio",
        },
      },
      {
        id: "stop3",
        name: "Local Jewelry Designers",
        description: "Custom jewelry and unique accessories",
        duration: "30m",
        location: "Sheung Wan",
        category: "shopping",
        order: 3,
        nextTransport: {
          method: "walk",
          duration: "8m",
          distance: "400m",
          instructions: "Walk to concept store",
        },
      },
      {
        id: "stop4",
        name: "Concept Store",
        description: "Curated lifestyle products and local brands",
        duration: "30m",
        location: "Sheung Wan",
        category: "shopping",
        order: 4,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Comedy & Entertainment Night",
    description: "Experience local comedy shows and entertainment venues",
    duration: "3h 45m",
    category: "entertainment",
    isPremium: false,
    isLocked: false,
    tokenCost: 0,
    transportMode: ["walk", "car"],
    itinerary: [
      {
        id: "stop1",
        name: "Comedy Club",
        description: "Stand-up comedy show with local and international acts",
        duration: "1h 30m",
        location: "Central",
        category: "entertainment",
        order: 1,
        nextTransport: {
          method: "car",
          duration: "10m",
          distance: "3km",
          instructions: "Take taxi to Causeway Bay entertainment district",
        },
      },
      {
        id: "stop2",
        name: "Karaoke Lounge",
        description: "Premium karaoke experience with private rooms",
        duration: "1h 15m",
        location: "Causeway Bay",
        category: "entertainment",
        order: 2,
        nextTransport: {
          method: "walk",
          duration: "5m",
          distance: "300m",
          instructions: "Walk to nearby arcade",
        },
      },
      {
        id: "stop3",
        name: "Retro Arcade",
        description: "Classic arcade games and nostalgic entertainment",
        duration: "45m",
        location: "Causeway Bay",
        category: "entertainment",
        order: 3,
        nextTransport: {
          method: "walk",
          duration: "3m",
          distance: "150m",
          instructions: "Walk to late-night bar",
        },
      },
      {
        id: "stop4",
        name: "Late Night Bar",
        description: "Cocktails and nightcap to end the evening",
        duration: "15m",
        location: "Causeway Bay",
        category: "entertainment",
        order: 4,
        nextTransport: null,
      },
    ],
  },
  {
    name: "Urban Gardening Tour",
    description: "Visit rooftop gardens and urban farming initiatives",
    duration: "2h 45m",
    category: "nature",
    isPremium: false,
    isLocked: false,
    tokenCost: 0,
    transportMode: ["walk", "car"],
    itinerary: [
      {
        id: "stop1",
        name: "Rooftop Garden",
        description: "Urban farming showcase with sustainable practices",
        duration: "1h",
        location: "Central",
        category: "nature",
        order: 1,
        nextTransport: {
          method: "walk",
          duration: "12m",
          distance: "800m",
          instructions: "Walk to Wan Chai through Admiralty",
        },
      },
      {
        id: "stop2",
        name: "Community Garden",
        description: "Local gardening initiative and volunteer programs",
        duration: "45m",
        location: "Wan Chai",
        category: "nature",
        order: 2,
        nextTransport: {
          method: "walk",
          duration: "8m",
          distance: "500m",
          instructions: "Walk to vertical garden installation",
        },
      },
      {
        id: "stop3",
        name: "Vertical Garden Wall",
        description: "Innovative vertical farming and green architecture",
        duration: "30m",
        location: "Wan Chai",
        category: "nature",
        order: 3,
        nextTransport: {
          method: "walk",
          duration: "5m",
          distance: "200m",
          instructions: "Walk to organic market",
        },
      },
      {
        id: "stop4",
        name: "Organic Farmers Market",
        description: "Local organic produce and gardening supplies",
        duration: "30m",
        location: "Wan Chai",
        category: "nature",
        order: 4,
        nextTransport: null,
      },
    ],
  },
];

async function seedTrips() {
  console.log("Starting to seed trips...");

  try {
    for (const tripData of sampleTrips) {
      const trip = {
        id: nanoid(),
        name: tripData.name,
        description: tripData.description,
        duration: tripData.duration,
        rating: Math.random() * 2 + 3, // Random rating between 3.5 and 5
        reviewCount: Math.floor(Math.random() * 200) + 20, // Random review count between 20 and 220
        isPremium: tripData.isPremium,
        isLocked: tripData.isLocked,
        tokenCost: [2, 3, 4, 5, 6, 7, 8, 9, 10][Math.floor(Math.random() * 9)],
        category: tripData.category,
        transportMode: JSON.stringify(tripData.transportMode),
        accessibility: JSON.stringify({
          visuallyImpaired: Math.random() > 0.5,
          wheelchairAccessible: Math.random() > 0.3,
        }),
        imageUrl: `/api/placeholder/300/200`,
        itinerary: JSON.stringify(tripData.itinerary),
        metadata: JSON.stringify({
          featured: Math.random() > 0.7,
          difficulty: Math.random() > 0.5 ? "easy" : "moderate",
        }),
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      await db.insert(trips).values(trip);
      console.log(`✓ Seeded trip: ${trip.name}`);
    }

    console.log(`\n🎉 Successfully seeded ${sampleTrips.length} trips!`);
  } catch (error) {
    console.error("Error seeding trips:", error);
  }
}

if (require.main === module) {
  seedTrips();
}

export { seedTrips };
